"""Added creator_color

Revision ID: 21c2c9adca8b
Revises: 9fca5b5bb8e3
Create Date: 2023-08-24 12:35:59.510093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c2c9adca8b'
down_revision = '9fca5b5bb8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_color', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('creator_color')

    # ### end Alembic commands ###
