"""Added fen column

Revision ID: 9fca5b5bb8e3
Revises: 
Create Date: 2023-08-24 11:20:39.072882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fca5b5bb8e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fen', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('white_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('black_time', sa.Integer(), nullable=True))
        batch_op.alter_column('current_state',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('current_state',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('black_time')
        batch_op.drop_column('white_time')
        batch_op.drop_column('fen')

    # ### end Alembic commands ###
